/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetsState: typeof import('./src/components/AssetsState.vue')['default']
    AssetsValues: typeof import('./src/components/AssetsValues.vue')['default']
    DeleteConfirmationDialog: typeof import('./src/components/DeleteConfirmationDialog.vue')['default']
    DictionaryPage: typeof import('./src/components/DictionaryPage.vue')['default']
    FormDialog: typeof import('./src/components/FormDialog.vue')['default']
    FormItem: typeof import('./src/components/FormItem.vue')['default']
    PortfolioPage: typeof import('./src/components/PortfolioPage.vue')['default']
    StructureCategories: typeof import('./src/components/StructureCategories.vue')['default']
  }
}
