name: Frontend tests
on:
  push:
    branches: [ main ]
    paths:
      - frontend/**
      - .github/workflows/jest.yml
  pull_request:
    branches: [ main ]
    paths:
      - frontend/**
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          cd frontend/
          npm ci
      - name: Run Jest tests
        run: |
          cd frontend/
          npm run test:jest
