name: Frontend tests
on:
  push:
    branches: [ main ]
    paths:
      - frontend/**
  pull_request:
    branches: [ main ]
    paths:
      - frontend/**
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          cd frontend/
          npm ci
      - name: Run Jest tests
        run: npm run test:jest -- --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
