name: Frontend e2e tests
on:
  push:
    branches: [ main ]
    paths:
      - frontend/**
      - .github/workflows/playwright.yml
  pull_request:
    branches: [ main ]
    paths:
      - frontend/**
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          cd frontend/
          npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Reinstall sqlite3
        run: |
          download_link="https://www.sqlite.org/2024/sqlite-tools-linux-x64-3470100.zip"
          wget "$download_link" -P /tmp
          unzip "/tmp/$(basename "$download_link")" -d /tmp
          sudo install /tmp/sqlite3 /usr/local/bin/
      - name: Install python dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          nohup uvicorn app:fastapi_app &
      - name: Run Playwright tests
        run: |
          cd ../frontend/
          nohup python -m http.server &
          npm run test:playwright
