name: Backend tests
on:
  push:
    branches: [ main ]
    paths:
      - backend/**
      - .github/workflows/pytest.yml
  pull_request:
    branches: [ main ]
    paths:
      - backend/**
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Reinstall sqlite3
        run: |
          download_link="https://www.sqlite.org/2024/sqlite-tools-linux-x64-3470100.zip"
          wget "$download_link" -P /tmp
          unzip "/tmp/$(basename "$download_link")" -d /tmp
          sudo install /tmp/sqlite3 /usr/local/bin/
      - name: Install dependencies and test
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          ENVIRONMENT=test pytest tests/ --doctest-modules --junitxml=junit.xml -o junit_family=legacy --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
